/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedListenRouteImport } from './routes/_authenticated/listen'
import { Route as AuthenticatedMomentsRouteImport } from './routes/_authenticated/moments'
import { Route as AuthenticatedPersonaRouteImport } from './routes/_authenticated/persona'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWallpaperRouteImport } from './routes/_authenticated/wallpaper'
import { Route as AuthenticatedDiaryIndexRouteImport } from './routes/_authenticated/diary.index'
import { Route as AuthenticatedDiaryNewRouteImport } from './routes/_authenticated/diary.new'
import { Route as AuthenticatedDiaryIdIndexRouteImport } from './routes/_authenticated/diary.$id.index'
import { Route as AuthenticatedDiaryIdEditRouteImport } from './routes/_authenticated/diary.$id.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListenRoute = AuthenticatedListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentsRoute = AuthenticatedMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonaRoute = AuthenticatedPersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWallpaperRoute = AuthenticatedWallpaperRouteImport.update({
  id: '/wallpaper',
  path: '/wallpaper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryIndexRoute = AuthenticatedDiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryNewRoute = AuthenticatedDiaryNewRouteImport.update({
  id: '/diary/new',
  path: '/diary/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryIdIndexRoute =
  AuthenticatedDiaryIdIndexRouteImport.update({
    id: '/diary/$id/',
    path: '/diary/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiaryIdEditRoute =
  AuthenticatedDiaryIdEditRouteImport.update({
    id: '/diary/$id/edit',
    path: '/diary/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/listen': typeof AuthenticatedListenRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/persona': typeof AuthenticatedPersonaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallpaper': typeof AuthenticatedWallpaperRoute
  '/diary/new': typeof AuthenticatedDiaryNewRoute
  '/diary/': typeof AuthenticatedDiaryIndexRoute
  '/diary/$id/edit': typeof AuthenticatedDiaryIdEditRoute
  '/diary/$id/': typeof AuthenticatedDiaryIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/listen': typeof AuthenticatedListenRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/persona': typeof AuthenticatedPersonaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallpaper': typeof AuthenticatedWallpaperRoute
  '/': typeof AuthenticatedIndexRoute
  '/diary/new': typeof AuthenticatedDiaryNewRoute
  '/diary': typeof AuthenticatedDiaryIndexRoute
  '/diary/$id/edit': typeof AuthenticatedDiaryIdEditRoute
  '/diary/$id': typeof AuthenticatedDiaryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/listen': typeof AuthenticatedListenRoute
  '/_authenticated/moments': typeof AuthenticatedMomentsRoute
  '/_authenticated/persona': typeof AuthenticatedPersonaRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallpaper': typeof AuthenticatedWallpaperRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/diary/new': typeof AuthenticatedDiaryNewRoute
  '/_authenticated/diary/': typeof AuthenticatedDiaryIndexRoute
  '/_authenticated/diary/$id/edit': typeof AuthenticatedDiaryIdEditRoute
  '/_authenticated/diary/$id/': typeof AuthenticatedDiaryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/chat'
    | '/focus'
    | '/listen'
    | '/moments'
    | '/persona'
    | '/profile'
    | '/settings'
    | '/wallpaper'
    | '/diary/new'
    | '/diary/'
    | '/diary/$id/edit'
    | '/diary/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai-settings'
    | '/chat'
    | '/focus'
    | '/listen'
    | '/moments'
    | '/persona'
    | '/profile'
    | '/settings'
    | '/wallpaper'
    | '/'
    | '/diary/new'
    | '/diary'
    | '/diary/$id/edit'
    | '/diary/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-settings'
    | '/_authenticated/chat'
    | '/_authenticated/focus'
    | '/_authenticated/listen'
    | '/_authenticated/moments'
    | '/_authenticated/persona'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/wallpaper'
    | '/_authenticated/'
    | '/_authenticated/diary/new'
    | '/_authenticated/diary/'
    | '/_authenticated/diary/$id/edit'
    | '/_authenticated/diary/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listen': {
      id: '/_authenticated/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof AuthenticatedListenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments': {
      id: '/_authenticated/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AuthenticatedMomentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/persona': {
      id: '/_authenticated/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof AuthenticatedPersonaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallpaper': {
      id: '/_authenticated/wallpaper'
      path: '/wallpaper'
      fullPath: '/wallpaper'
      preLoaderRoute: typeof AuthenticatedWallpaperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary/': {
      id: '/_authenticated/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof AuthenticatedDiaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary/new': {
      id: '/_authenticated/diary/new'
      path: '/diary/new'
      fullPath: '/diary/new'
      preLoaderRoute: typeof AuthenticatedDiaryNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary/$id/': {
      id: '/_authenticated/diary/$id/'
      path: '/diary/$id'
      fullPath: '/diary/$id/'
      preLoaderRoute: typeof AuthenticatedDiaryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary/$id/edit': {
      id: '/_authenticated/diary/$id/edit'
      path: '/diary/$id/edit'
      fullPath: '/diary/$id/edit'
      preLoaderRoute: typeof AuthenticatedDiaryIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedListenRoute: typeof AuthenticatedListenRoute
  AuthenticatedMomentsRoute: typeof AuthenticatedMomentsRoute
  AuthenticatedPersonaRoute: typeof AuthenticatedPersonaRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWallpaperRoute: typeof AuthenticatedWallpaperRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDiaryNewRoute: typeof AuthenticatedDiaryNewRoute
  AuthenticatedDiaryIndexRoute: typeof AuthenticatedDiaryIndexRoute
  AuthenticatedDiaryIdEditRoute: typeof AuthenticatedDiaryIdEditRoute
  AuthenticatedDiaryIdIndexRoute: typeof AuthenticatedDiaryIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedListenRoute: AuthenticatedListenRoute,
  AuthenticatedMomentsRoute: AuthenticatedMomentsRoute,
  AuthenticatedPersonaRoute: AuthenticatedPersonaRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWallpaperRoute: AuthenticatedWallpaperRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDiaryNewRoute: AuthenticatedDiaryNewRoute,
  AuthenticatedDiaryIndexRoute: AuthenticatedDiaryIndexRoute,
  AuthenticatedDiaryIdEditRoute: AuthenticatedDiaryIdEditRoute,
  AuthenticatedDiaryIdIndexRoute: AuthenticatedDiaryIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
